### ISSUE TITLE
pylibssh does not connect over bastion host

### ISSUE THREAD

**Issue by ghost** [ansible/pylibssh#326]
##### SUMMARY
When using __ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -p {{ bastion_port }} {{ bastion_user }}@{{ bastion_host }}"'__ for issuing a connection over a bastion host, sshlib fails with an error. It says that the remote host is not resolvable. As a result the ansible task fails as Ansible is not able to connect to the remote host over the bastion host.

##### ISSUE TYPE
- Bug Report

##### PYLISSH and LIBSSH VERSION

```
version 0.4.0
```

##### OS / ENVIRONMENT
```
AlmaLinux release 8.5 (Arctic Sphynx)
ansible [core 2.12.4]
  config file = /home/ansible/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.9.6 (default, Oct 10 2021, 07:39:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.1
  libyaml = True
 python -m pip list
	Package          Version
	---------------- -------
	ansible          5.6.0
	ansible-core     2.12.4
	ansible-pylibssh 0.4.0
	bcrypt           3.2.0
	cffi             1.15.0
	cryptography     36.0.2
	distlib          0.3.4
	filelock         3.6.0
	Jinja2           3.1.1
	MarkupSafe       2.1.1
	packaging        21.3
	paramiko         2.10.3
	pip              22.0.4
	platformdirs     2.5.2
	pycparser        2.21
	PyNaCl           1.5.0
	pyparsing        3.0.7
	PyYAML           6.0
	resolvelib       0.5.4
	setuptools       50.3.2
	six              1.16.0
	virtualenv       20.14.1
```

##### STEPS TO REPRODUCE

Reproducing the problem needs a setup which could use a bastion (jump) host for communication. In our setup we use a variety of jumphosts and set the correspoining jumphost by using variables in group_vars. For example_
__ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -p {{ bastion_port }} {{ bastion_user }}@{{ bastion_host }}"'__. In the test environment we try to connect to a Cisco IOS based switch through a bastion host, wich was no problem in prior ansible versions using paramiko.

##### EXPECTED RESULTS
Expected result is that ansible connects to the bastion host, on the bastion host the name resolving is done for the target host and then ansible connects through the bastion to the target host.

##### ACTUAL RESULTS
Ansible does name resolution locally, which leads to unknown service in connection.

```2022-05-09 09:27:53,747 p=110739 u=ansible n=ansible | ansible-playbook [core 2.12.4]
  config file = /home/ansible/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible-playbook
  python version = 3.9.6 (default, Oct 10 2021, 07:39:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.1
  libyaml = True
2022-05-09 09:27:53,748 p=110739 u=ansible n=ansible | Using /home/ansible/ansible/ansible.cfg as config file
2022-05-09 09:27:53,749 p=110739 u=ansible n=ansible | setting up inventory plugins
2022-05-09 09:27:53,757 p=110739 u=ansible n=ansible | host_list declined parsing /home/ansible/ansible/hosts.py as it did not pass its verify_file() method
2022-05-09 09:28:03,993 p=110739 u=ansible n=ansible | Parsed /home/ansible/ansible/hosts.py inventory source with script plugin
2022-05-09 09:28:04,538 p=110739 u=ansible n=ansible | redirecting (type: modules) ansible.builtin.ios_config to cisco.ios.ios_config
2022-05-09 09:28:04,541 p=110739 u=ansible n=ansible | Loading collection cisco.ios from /home/ansible/.ansible/collections/ansible_collections/cisco/ios
2022-05-09 09:28:04,546 p=110739 u=ansible n=ansible | Loading callback plugin default of type stdout, v2.0 from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/callback/default.py
2022-05-09 09:28:04,557 p=110739 u=ansible n=ansible | Skipping callback 'default', as we already have a stdout callback.
2022-05-09 09:28:04,557 p=110739 u=ansible n=ansible | Skipping callback 'minimal', as we already have a stdout callback.
2022-05-09 09:28:04,557 p=110739 u=ansible n=ansible | Skipping callback 'oneline', as we already have a stdout callback.
2022-05-09 09:28:04,557 p=110739 u=ansible n=ansible | PLAYBOOK: save-1100.yml ***********************************************************************************************************************************************************************************************
2022-05-09 09:28:04,558 p=110739 u=ansible n=ansible | 1 plays in playbooks/save-1100.yml
2022-05-09 09:28:04,562 p=110739 u=ansible n=ansible | PLAY [initial configuration] ******************************************************************************************************************************************************************************************
2022-05-09 09:28:04,572 p=110739 u=ansible n=ansible | META: ran handlers
2022-05-09 09:28:04,576 p=110739 u=ansible n=ansible | TASK [Configbackup] ***************************************************************************************************************************************************************************************************
2022-05-09 09:28:04,595 p=111096 u=ansible n=ansible | Loading collection ansible.netcommon from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon
2022-05-09 09:28:04,620 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> attempting to start connection
2022-05-09 09:28:04,620 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> using connection plugin ansible.netcommon.network_cli
2022-05-09 09:28:04,620 p=111096 u=ansible n=ansible | Found ansible-connection at path /home/ansible/.local/bin/ansible-connection
2022-05-09 09:28:05,032 p=111101 u=ansible n=ansible | Loading collection ansible.netcommon from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon
2022-05-09 09:28:05,056 p=111101 u=ansible n=ansible | Loading collection cisco.ios from /home/ansible/.ansible/collections/ansible_collections/cisco/ios
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> local domain socket does not exist, starting it
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> control socket path is /home/ansible/.ansible/pc/45c1efc477
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.00983: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.00998: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.02032: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.02081: Loading ModuleDocFragment 'connection_pipelining' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments/connection_pipelining.py
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.02136: Loading ModuleDocFragment 'connection_ssh_args' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments/connection_ssh_args.py
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.02204: Loaded config def from plugin (connection/ssh)
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.02210: Loading Connection 'ssh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/ssh.py (searched paths: /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection:/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__) (found_in_cache=False, class_only=True)
2022-05-09 09:28:05,135 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> Loading collection ansible.netcommon from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.04852: Loading ModuleDocFragment 'ansible_collections.ansible.netcommon.plugins.doc_fragments.connection_persistent' from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/doc_fragments/connection_persistent.py
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.04920: Loaded config def from plugin (connection/ansible_collections.ansible.netcommon.plugins.connection.network_cli)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.04927: Loading Connection 'ansible_collections.ansible.netcommon.plugins.connection.network_cli' from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py (searched paths: /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection:/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.04979: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05050: Loading ModuleDocFragment 'shell_common' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments/shell_common.py
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05166: Loaded config def from plugin (shell/sh)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05170: Loading ShellModule 'sh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell/sh.py
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05177: Loading ShellModule 'sh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05233: Loading ModuleDocFragment 'connection_pipelining' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments/connection_pipelining.py (found_in_cache=True, class_only=False)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05259: Loaded config def from plugin (connection/local)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05264: Loading Connection 'local' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/local.py (searched paths: /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection:/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05271: Loading ShellModule 'sh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05275: Loading ShellModule 'sh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05315: Loading Connection 'ssh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/ssh.py (searched paths: /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection:/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__) (found_in_cache=True, class_only=True)
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> Loading collection cisco.ios from /home/ansible/.ansible/collections/ansible_collections/cisco/ios
2022-05-09 09:28:05,136 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.05935: Loading TerminalModule 'ansible_collections.cisco.ios.plugins.terminal.ios' from /home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/terminal/ios.py
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.06380: Loaded config def from plugin (cliconf/ansible_collections.cisco.ios.plugins.cliconf.ios)
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.06385: Loading Cliconf 'ansible_collections.cisco.ios.plugins.cliconf.ios' from /home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.07019: Loaded config def from plugin (connection/ansible_collections.ansible.netcommon.plugins.connection.libssh)
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.07026: Loading Connection 'ansible_collections.ansible.netcommon.plugins.connection.libssh' from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/libssh.py (searched paths: /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection:/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__)
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.07034: Loading ShellModule 'sh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111101 1652081285.07039: Loading ShellModule 'sh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> local domain socket listeners started successfully
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | network_os is set to cisco.ios.ios
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> ssh type is set to libssh
2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> 111097 1652081285.00983: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__
111097 1652081285.00998: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection
111097 1652081285.02032: trying /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments
111097 1652081285.02081: Loading ModuleDocFragment 'connection_pipelining' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments/connection_pipelining.py
111097 1652081285.02136: Loading ModuleDocFragment 'connection_ssh_args' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/doc_fragments/connection_ssh_args.py
111097 1652081285.02204: Loaded config def from plugin (connection/ssh)
111097 1652081285.02210: Loading Connection 'ssh' from /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/ssh.py (searched paths: /home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection:/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/connection/__pycache__) (found_in_cache=False, class_only=True)

2022-05-09 09:28:05,137 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> local domain socket path is /home/ansible/.ansible/pc/45c1efc477
2022-05-09 09:28:05,148 p=111096 u=ansible n=ansible | redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
2022-05-09 09:28:05,148 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> Using network group action ios for ios_config
2022-05-09 09:28:05,148 p=111096 u=ansible n=ansible | redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
2022-05-09 09:28:05,154 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
2022-05-09 09:28:05,154 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
2022-05-09 09:28:05,154 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> ESTABLISH LOCAL CONNECTION FOR USER: ansible
2022-05-09 09:28:05,155 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn `"&& mkdir "` echo /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345 `" && echo ansible-tmp-1652081285.1545424-111096-47310360996345="` echo /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345 `" ) && sleep 0'
2022-05-09 09:28:05,168 p=111096 u=ansible n=ansible | redirecting (type: modules) ansible.builtin.ios_config to cisco.ios.ios_config
2022-05-09 09:28:05,289 p=111096 u=ansible n=ansible | Using module file /home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_config.py
2022-05-09 09:28:05,290 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> PUT /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/tmpjlal7cna TO /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345/AnsiballZ_ios_config.py
2022-05-09 09:28:05,290 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345/ /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345/AnsiballZ_ios_config.py && sleep 0'
2022-05-09 09:28:05,301 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> EXEC /bin/sh -c '/bin/python /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345/AnsiballZ_ios_config.py && sleep 0'
2022-05-09 09:28:05,513 p=111101 u=ansible n=ansible | <a-host.parrot.intranet> ESTABLISH LIBSSH CONNECTION FOR USER: nannyplum on PORT 22 TO a-host.parrot.intranet
2022-05-09 09:28:05,513 p=111101 u=ansible n=ansible | ESTABLISH LIBSSH CONNECTION WITH VARS:
2022-05-09 09:28:05,518 p=111101 u=ansible n=ansible | Traceback (most recent call last):
  File "/home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/libssh.py", line 346, in _connect_uncached
    self.ssh.connect(
  File "src/pylibsshext/session.pyx", line 239, in pylibsshext.session.Session.connect
pylibsshext.errors.LibsshSessionException: ssh connect failed: Failed to resolve hostname a-host.parrot.intranet (Name or service not known)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ansible/.local/lib/python3.9/site-packages/ansible/utils/jsonrpc.py", line 46, in handle_request
    result = rpc_method(*args, **kwargs)
  File "/home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py", line 348, in get_capabilities
    result = super(Cliconf, self).get_capabilities()
  File "/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/cliconf/__init__.py", line 283, in get_capabilities
    result['device_info'] = self.get_device_info()
  File "/home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py", line 295, in get_device_info
    reply = self.get(command="show version")
  File "/home/ansible/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py", line 273, in get
    return self.send_command(
  File "/home/ansible/.local/lib/python3.9/site-packages/ansible/plugins/cliconf/__init__.py", line 127, in send_command
    resp = self._connection.send(**kwargs)
  File "/home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 335, in wrapped
    self._connect()
  File "/home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 597, in _connect
    ssh = self.ssh_type_conn._connect()
  File "/home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/libssh.py", line 248, in _connect
    ] = self._connect_uncached()
  File "/home/ansible/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/libssh.py", line 359, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
ansible.errors.AnsibleConnectionFailure: ssh connection failed: ssh connect failed: Failed to resolve hostname a-host.parrot.intranet (Name or service not known)

2022-05-09 09:28:05,538 p=111096 u=ansible n=ansible | <a-host.parrot.intranet> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-local-110739946ma2vn/ansible-tmp-1652081285.1545424-111096-47310360996345/ > /dev/null 2>&1 && sleep 0'
2022-05-09 09:28:05,552 p=110739 u=ansible n=ansible | The full traceback is:
  File "/tmp/ansible_ios_config_payload_fwxk9a34/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 94, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_ios_config_payload_fwxk9a34/ansible_ios_config_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

2022-05-09 09:28:05,552 p=110739 u=ansible n=ansible | fatal: [a-host.parrot.intranet]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "backup": true,
            "backup_options": {
                "dir_path": "/home/ansible/configrepo/parrot",
                "filename": "a-host.parrot.intranet.tmp"
            },
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "intended_config": null,
            "lines": null,
            "match": "line",
            "multiline_delimiter": "@",
            "parents": null,
            "provider": null,
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "src": null
        }
    },
    "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname a-host.parrot.intranet (Name or service not known)"
}
2022-05-09 09:28:05,555 p=110739 u=ansible n=ansible | PLAY RECAP ************************************************************************************************************************************************************************************************************
2022-05-09 09:28:05,555 p=110739 u=ansible n=ansible | a-host.parrot.intranet       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
2022-05-09 09:28:05,655 p=111101 u=ansible n=ansible | shutdown complete
```

**Comment by ghost** [comment]
> @krlSPRwld Does this work fine for you with paramiko? If not, then this is most likely related to [ansible-collections/ansible.netcommon#296](https://github.com/ansible-collections/ansible.netcommon/issues/296).

@NilashishC, yes with paramiko everything works as expected. This is an issue lokated in libssh, which is behaving different.

**Comment by Qalthos** [comment]
This is in fact an issue with libssh, but the connection plugin, not the library or our wrapper. Closing in favor of https://github.com/ansible-collections/ansible.netcommon/issues/296.
